//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OngCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int CursoId { get; set; }
        public string NomeCurso { get; set; }
        public string Professor { get; set; }
        public string Status { get; set; }
    }
}
