//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OngCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int FuncID { get; set; }
        public string Nome { get; set; }
        public string Cargo { get; set; }
        public string Sede { get; set; }
        public Nullable<int> Idade { get; set; }
        public Nullable<int> Salario { get; set; }
    }
}
